import { Scene } from './types'

export const scenes: Scene[] = [
  {
    skyBg: '#5C3A1E',
    time: '07:45 · your bedroom',
    timeSub: 'the day begins',
    question: "There's a test today. Your alarm just went off.",
    context: "You studied last night — not as much as you meant to. You have 45 minutes before you need to leave.",
    researchNote: "How people respond to morning academic pressure predicts end-of-term performance more reliably than weekly study hours.",
    researchRef: "Duckworth et al., 2019 · PNAS",
    portraitStroke: 'arc',
    strokeColour: '#7F77DD',
    choices: [
      {
        letter: 'A',
        main: 'Cram hard — go through everything fast',
        sub: 'Absorb as much as possible before the bell.',
        reveal: 'Urgency as strategy. This tells us about your relationship with pressure — you move toward it rather than away from it.',
        revealSub: 'High drive. Consistency takes a hit.',
        scores: { drive: 3, consistency: -1, selfAware: -1 },
        energy: 0.85,
      },
      {
        letter: 'B',
        main: '30-minute focused review, then leave calmly',
        sub: "You've done what you can. Panic won't help.",
        reveal: 'Measured. This is someone who knows where the line of diminishing returns is — and stops before they cross it.',
        revealSub: 'Balance between effort and self-regulation.',
        scores: { drive: 2, consistency: 2, selfAware: 2 },
        energy: 0.7,
      },
      {
        letter: 'C',
        main: "Skip it. You know it or you don't.",
        sub: 'Accept where you are. Save your energy.',
        reveal: 'Acceptance — or avoidance. Only the rest of the day will tell us which one this actually is.',
        revealSub: 'Self-awareness present. Drive not activated.',
        scores: { drive: -2, consistency: -1, selfAware: 1 },
        energy: 0.3,
      },
      {
        letter: 'D',
        main: 'Organise your notes for next time instead',
        sub: "This test might be a write-off. But you're already thinking forward.",
        reveal: "Choosing the long game over the short one. That's a particular kind of intelligence that doesn't show up on most assessments.",
        revealSub: 'High self-awareness. Strong consistency signal.',
        scores: { drive: 1, consistency: 3, selfAware: 3 },
        energy: 0.6,
      },
    ],
  },
  {
    skyBg: '#0C3A6B',
    time: '09:20 · maths class',
    timeSub: 'mid-morning',
    question: 'Teacher asks a question. You think you know the answer.',
    context: "The room is quiet. Nobody's volunteering. You're about 80% sure you're right.",
    researchNote: 'The act of raising your hand changes how information is encoded in memory — participation is an active learning mechanism, not just a social performance.',
    researchRef: 'Finn & Zimmer, 2012 · APA',
    portraitStroke: 'eye',
    strokeColour: '#1D9E75',
    choices: [
      {
        letter: 'A',
        main: "Hand up. You might be wrong. You're willing to find out.",
        sub: '',
        reveal: "This is the choice most people don't make. The willingness to be publicly wrong is one of the most underrated academic skills.",
        revealSub: 'Confidence and leadership both activated.',
        scores: { confidence: 3, leadership: 2, drive: 1 },
        energy: 0.9,
      },
      {
        letter: 'B',
        main: 'Stay quiet — wait to see if you were right',
        sub: "Risk-free. You'll learn the answer either way.",
        reveal: "Risk management. The knowledge is there but the self-belief doesn't follow it into the open.",
        revealSub: 'Self-aware but confidence is guarded.',
        scores: { confidence: -1, leadership: -1, selfAware: 1 },
        energy: 0.4,
      },
      {
        letter: 'C',
        main: 'Whisper your answer to the person next to you first',
        sub: 'Test it privately before going public.',
        reveal: 'A stepping stone. You needed one layer of safety before the bigger move — which is completely understandable.',
        revealSub: 'Cautious confidence. Self-awareness high.',
        scores: { confidence: 1, leadership: 1, selfAware: 2 },
        energy: 0.6,
      },
      {
        letter: 'D',
        main: 'Miles away — thinking about something else',
        sub: 'It happens.',
        reveal: 'The mind was somewhere else entirely. Worth asking: when does school actually hold your full attention?',
        revealSub: 'Engagement gap. No judgment — just a signal.',
        scores: { confidence: -1, drive: -2, consistency: -1 },
        energy: 0.2,
      },
    ],
  },
  {
    skyBg: '#1A3D1A',
    time: '12:05 · the canteen',
    timeSub: 'lunchtime',
    question: "Your group project partner is sitting alone. The project is due Friday. You're behind.",
    context: "You have your own lunch, your own thoughts. But the project isn't going to fix itself.",
    researchNote: "Proactive collaboration behaviour is a stronger predictor of group success than any individual member's skill level.",
    researchRef: 'Woolley et al., 2010 · Science (collective intelligence study)',
    portraitStroke: 'line',
    strokeColour: '#D85A30',
    choices: [
      {
        letter: 'A',
        main: 'Sit with them and bring up the project directly',
        sub: 'Awkward maybe. But honest.',
        reveal: "You moved toward the discomfort instead of away from it. That's what leadership actually looks like before anyone calls it that.",
        revealSub: 'Leadership and consistency at full strength.',
        scores: { leadership: 3, consistency: 2, confidence: 2 },
        energy: 0.9,
      },
      {
        letter: 'B',
        main: "Sit nearby but don't mention it",
        sub: "Nice to not be alone. One more day won't hurt.",
        reveal: "Proximity without commitment. The intention was probably there — but the follow-through wasn't.",
        revealSub: 'Avoidance pattern. Mild but noted.',
        scores: { leadership: -1, consistency: -1 },
        energy: 0.45,
      },
      {
        letter: 'C',
        main: 'Text them later to schedule something',
        sub: 'More comfortable than face-to-face.',
        reveal: "Asynchronous initiative. Not the boldest move, but it's still a move in the right direction.",
        revealSub: 'Moderate consistency. Lower-friction path chosen.',
        scores: { leadership: 1, consistency: 1 },
        energy: 0.55,
      },
      {
        letter: 'D',
        main: "Sit somewhere else — you need this break",
        sub: "You can only help others if you're okay yourself.",
        reveal: "Self-preservation over obligation. That's a legitimate choice — but it's part of a pattern worth seeing.",
        revealSub: 'Self-awareness high. Leadership not activated.',
        scores: { leadership: -1, selfAware: 2 },
        energy: 0.35,
      },
    ],
  },
  {
    skyBg: '#6B3A0C',
    time: '15:30 · after school',
    timeSub: 'the real test',
    question: 'Two free hours. No plan. What actually happens?',
    context: "Be honest. This is the question people lie most about on questionnaires. Nobody's watching.",
    researchNote: 'Self-reported vs. actual after-school behaviour diverges by an average of 40% in diary studies — people systematically overestimate their own productivity.',
    researchRef: 'Larson & Richards, 1991 · Developmental Psychology',
    portraitStroke: 'ground',
    strokeColour: '#EF9F27',
    choices: [
      {
        letter: 'A',
        main: 'Homework straight away — get it done',
        sub: 'The evening is yours.',
        reveal: "The afternoon is where most students' intentions collapse. Yours didn't. This is the single most predictive signal in the whole assessment.",
        revealSub: 'Consistency and drive both at peak.',
        scores: { drive: 3, consistency: 3, selfAware: 1 },
        energy: 0.9,
      },
      {
        letter: 'B',
        main: 'Go to a club, sport, or activity',
        sub: "Whatever your thing is — you're there.",
        reveal: 'Structured commitment outside the classroom. Extracurricular consistency is one of the strongest non-academic predictors of long-term outcomes.',
        revealSub: 'Engagement strong. Consistency present.',
        scores: { extracurricular: 3, leadership: 1, consistency: 2 },
        energy: 0.85,
      },
      {
        letter: 'C',
        main: 'Decompress first, then probably get going',
        sub: 'One hour of your phone. Then work.',
        reveal: "The most common answer. Whether the 'then work' actually happened is the question this assessment can't answer — but you can.",
        revealSub: 'Neutral signal. Honest and common.',
        scores: { selfAware: 1 },
        energy: 0.5,
      },
      {
        letter: 'D',
        main: 'Nothing productive happens',
        sub: "More often than you'd like to admit.",
        reveal: "The honesty here is actually a strong signal on its own. Most people would have chosen C. The fact that you didn't says something important.",
        revealSub: 'Consistency gap. Self-awareness notably high.',
        scores: { consistency: -2, drive: -1, selfAware: 2 },
        energy: 0.2,
      },
    ],
  },
  {
    skyBg: '#4A1A2E',
    time: '18:00 · a notification',
    timeSub: 'an opportunity appears',
    question: 'A school competition is announced. Students self-nominate.',
    context: "You'd probably be decent at it. Maybe even good. You have no idea if you'd win.",
    researchNote: 'Self-nomination behaviour in adolescence is a stronger predictor of long-term career trajectory than grades or standardised test scores.',
    researchRef: 'Judge & Bono, 2001 · Journal of Applied Psychology',
    portraitStroke: 'reach',
    strokeColour: '#D4537E',
    choices: [
      {
        letter: 'A',
        main: 'Name forward immediately',
        sub: "You might lose. That's not the point.",
        reveal: "You backed yourself before you were sure. In this entire dataset, that pattern is genuinely rare — and it matters more than people think.",
        revealSub: 'Confidence and leadership at maximum.',
        scores: { confidence: 3, leadership: 3, extracurricular: 2 },
        energy: 0.95,
      },
      {
        letter: 'B',
        main: 'Think about it — maybe sign up later',
        sub: 'You want to. You just want to be sure first.',
        reveal: "The hesitation is real. The question worth sitting with: does 'later' usually happen, for you?",
        revealSub: 'Moderate confidence. Self-aware about the gap.',
        scores: { confidence: 1, selfAware: 2 },
        energy: 0.6,
      },
      {
        letter: 'C',
        main: 'Decide against it — too much on already',
        sub: 'Not the right time.',
        reveal: "Boundary-setting or self-protection? The rest of the day's pattern will tell us which one is closer to the truth.",
        revealSub: 'Confidence not activated.',
        scores: { confidence: -1, leadership: -1, consistency: 1 },
        energy: 0.3,
      },
      {
        letter: 'D',
        main: 'Push a friend to enter instead',
        sub: 'You see potential in others before you see it in yourself.',
        reveal: 'Generative leadership — lifting others into the spotlight. But notice what you did with your own name in this moment.',
        revealSub: 'Interesting split: leads others, doubts self.',
        scores: { confidence: -1, leadership: 2, selfAware: 2 },
        energy: 0.45,
      },
    ],
  },
  {
    skyBg: '#0D0B1A',
    time: '22:30 · your room',
    timeSub: 'how it ends',
    question: "It's late. Tomorrow is a normal school day. How does the day end?",
    context: "The truest window into your habits isn't a survey question. It's this moment, right here.",
    researchNote: 'Sleep regularity correlates more strongly with GPA than total sleep hours — when and how you wind down matters more than how long you sleep.',
    researchRef: 'Phillips et al., 2017 · Scientific Reports (Harvard sleep study)',
    portraitStroke: 'close',
    strokeColour: '#378ADD',
    choices: [
      {
        letter: 'A',
        main: 'Homework done. Bag packed. Out soon.',
        sub: 'You have a system. It mostly works.',
        reveal: 'The day closed the way it opened — with intention. That loop, start to finish, is the clearest signal this assessment produces.',
        revealSub: 'Consistency confirmed across the full day.',
        scores: { drive: 2, consistency: 3, selfAware: 2 },
        energy: 0.9,
      },
      {
        letter: 'B',
        main: 'Finishing something you started too late',
        sub: "Deadline pressure is real. You're still getting it done.",
        reveal: "Reactive but functional. The work gets done — just not on your own timeline. That gap is worth thinking about.",
        revealSub: 'Moderate pattern. Honest close.',
        scores: { drive: 1, selfAware: 1 },
        energy: 0.6,
      },
      {
        letter: 'C',
        main: 'Still scrolling. Tomorrow can wait.',
        sub: "Not the plan. But it's the truth.",
        reveal: "The day drifted to a close. That's not a failure — but it's a pattern, and patterns have weight.",
        revealSub: 'Consistency gap confirmed at the close.',
        scores: { consistency: -2, selfAware: 1, drive: -1 },
        energy: 0.2,
      },
      {
        letter: 'D',
        main: 'Already asleep — passed out at 9',
        sub: 'Rest is productive. Or maybe you gave up.',
        reveal: "The body made the decision. Sometimes that's wisdom. Sometimes it's avoidance. Only you know which.",
        revealSub: 'Ambiguous close. Context is everything.',
        scores: { consistency: 1, selfAware: 1 },
        energy: 0.55,
      },
    ],
  },
]
